### ISSUE TITLE
💄 [UI] Text 컴포넌트 제작

### ISSUE THREAD

**Issue by eugene028** [Team-TIFY/TIFY-CLIENT#15]
# ✨ 어떤 작업인가요?
타이포를 편리하게 적용할 수 있는 Text 컴포넌트를 제작합니다.

# ☑ TODO
- [ ] typo 변경된 부분 수정
- [ ] 타이포 컴포넌트 생성 및 테스트
- [ ] 스토리북 작성, 빌드완료
