### ISSUE TITLE
💄 [UI] TodayCategory, TodayCategoryList, TodayList 컴포넌트 제작

### ISSUE THREAD

**Issue by ghdtjgus76** [Team-TIFY/TIFY-CLIENT#169]
## ✨ 어떤 작업인가요?
지난 투데이 페이지에 필요한 TodayCategory, TodayCategoryList, TodayList 컴포넌트를 제작합니다.

## ☑ TODO
- [X] TodayCategory 컴포넌트 제작
- [X] TodayCategoryList 컴포넌트 제작
- [X] TodayList 컴포넌트 제작
