### ISSUE TITLE
🐛 [Bug] Prettier가 정상적으로 작동하지 않는 부분 확인

### ISSUE THREAD

**Issue by eugene028** [Team-TIFY/TIFY-CLIENT#17]
# 🛠️ 어떤 버그를 고치나요?
Prettier가 정상적으로 작동하는 것으로 보이지 않아 고쳐야 합니다.

# ☑ TODOS
- [ ] yarn berry 환경에서 prettier가 어떻게 작동하는지 참고
- [ ] prettier 세팅 수정 
- [ ] eslint도 vscode 세팅 안쓰도록 해주기
