### ISSUE TITLE
🐛 [Bug] 친구 프로필 취향 정보 보이도록 수정 및 카테고리 에러 수정

### ISSUE THREAD

**Issue by ghdtjgus76** [Team-TIFY/TIFY-CLIENT#215]
## 🛠️ 어떤 버그를 고치나요?
친구 프로필에서 취향 정보가 안 보이는 문제와 카테고리 컴포넌트에서 선물하기 아이콘이 보이도록 수정해놨습니다.

## ☑ TODOS
- [x] 친구 프로필에서 취향 정보가 안 보이는 문제 해결
- [x] 친구 프로필 상 카테고리 컴포넌트에서 선물하기 아이콘이 보이도록 수정
- [x] 친구 프로필에서 선물하기 아이콘과 선물하기 페이지 연결
- [x] 내 프로필에서 + 아이콘과 질문 답변 페이지 연결
