### ISSUE TITLE
💄 [UI] 버튼 디자인 변경 대응 및 애니메이션 적용

### ISSUE THREAD

**Issue by eugene028** [Team-TIFY/TIFY-CLIENT#68]
## ✨ 어떤 작업인가요?
버튼 컴포넌트에서 추가된 다자인을 정리하고, 각 페이지에 알맞는 디자인으로 수정합니다 
또한 자연스러운 페이지 전환 효과를 위하여 애니메이션을 적용해봅니다. 
## ☑ TODO
- [x] framer-motion을 이용하여 각 페이지 전환별로 애니메이션 동작하는 부분 custom hook으로 분리
- [x] 버튼 컴포넌트 디자인 변경 대응
- [x] 에스코어드림 눈누폰트 404 에러 해결
